"use client";

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Slider } from '@/components/ui/slider';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from "@/hooks/use-toast";
import { syncToGithub } from '@/ai/flows/sync-to-github-flow';
import { 
  Gamepad2, 
  ArrowLeft, 
  Play, 
  Save, 
  Rocket, 
  Plus, 
  Layers, 
  Settings, 
  Code2, 
  Wand2, 
  ChevronRight,
  MousePointer2,
  Move,
  Type,
  ImageIcon,
  Zap,
  Box,
  Activity,
  Maximize2,
  Terminal,
  Cpu,
  RefreshCcw,
  Check,
  Github,
  Loader2
} from 'lucide-react';
import Link from 'next/link';

export default function GameEditor() {
  const [selectedElement, setSelectedElement] = useState<string | null>('Player');
  const [isSaving, setIsSaving] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const { toast } = useToast();
  
  // Script state
  const [scriptContent, setScriptContent] = useState(`extends CharacterBody2D

# Neural Constants Generated by AI
const SPEED = 300.0
const JUMP_FORCE = -400.0

var gravity = 980.0
var score = 0

func _physics_process(delta):
    # Apply Environmental Gravity
    if not is_on_floor():
        velocity.y += gravity * delta

    # Input Matrix Check
    if Input.is_action_just_pressed("jump") and is_on_floor():
        velocity.y = JUMP_FORCE
        play_sfx("jump")

    # Vector calculation
    var axis = Input.get_axis("ui_left", "ui_right")
    if axis:
        velocity.x = axis * SPEED
    else:
        velocity.x = move_toward(velocity.x, 0, SPEED * 0.1)

    # Core Execution
    move_and_slide()

func play_sfx(name):
    print("Playing SFX: " + name)`);

  // Properties state
  const [properties, setProperties] = useState({
    speed: 300,
    health: 100,
    gravity: 980,
    jumpForce: -400,
    color: '#0EA5E9'
  });

  const handleSave = () => {
    setIsSaving(true);
    setTimeout(() => {
      setIsSaving(false);
      toast({
        title: "Backup Local Atualizado",
        description: "As alterações foram salvas no cache do navegador.",
      });
    }, 1000);
  };

  const handleGithubSync = async () => {
    const token = localStorage.getItem('gh_token');
    const owner = localStorage.getItem('gh_user');
    const repo = localStorage.getItem('gh_repo');

    if (!token || !owner || !repo) {
      toast({
        variant: "destructive",
        title: "Integração GitHub Pendente",
        description: "Configure seu token e repositório na página de Configurações do Sistema.",
      });
      return;
    }

    setIsSyncing(true);
    try {
      const result = await syncToGithub({
        token,
        owner,
        repo,
        files: [
          { path: 'src/Player.gd', content: scriptContent },
          { path: 'project.godot', content: '; Godot Project Configuration\nconfig_version=5\n[application]\nconfig/name="AIGameForge Project"\n[display]\nwindow/size/viewport_width=1280\nwindow/size/viewport_height=720' }
        ],
        commitMessage: 'Auto-sync from AIGameForge: ' + new Date().toLocaleString()
      });

      if (result.success) {
        toast({
          title: "Sincronização Concluída",
          description: `Projeto enviado com sucesso para ${owner}/${repo}`,
        });
      } else {
        throw new Error(result.error);
      }
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Erro na Sincronização",
        description: error.message,
      });
    } finally {
      setIsSyncing(false);
    }
  };

  return (
    <div className="h-screen bg-[#020202] text-foreground flex flex-col overflow-hidden font-body">
      {/* Top Header - Pro HUD Theme */}
      <header className="h-14 border-b border-white/5 bg-black/80 backdrop-blur-2xl flex items-center px-4 justify-between shrink-0 z-50">
        <div className="flex items-center gap-3">
          <Link href="/dashboard">
            <Button variant="ghost" size="icon" className="h-9 w-9 text-white/40 hover:text-white hover:bg-white/10 rounded-lg transition-all">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div className="h-4 w-px bg-white/10 mx-1" />
          <div className="flex flex-col">
            <h1 className="font-headline font-bold text-[10px] text-white tracking-[0.2em] uppercase flex items-center gap-2">
              PROJECT_FORGE_V1 <span className="bg-primary/20 text-primary text-[8px] px-1.5 py-0.5 rounded border border-primary/20 animate-pulse">DEV_READY</span>
            </h1>
            <span className="text-[9px] text-white/30 font-mono">RES://SRC/PLAYER.GD</span>
          </div>
        </div>
        
        <div className="flex items-center gap-3">
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleGithubSync}
            disabled={isSyncing}
            className="h-9 bg-white/5 border-white/10 text-white font-bold text-[10px] uppercase tracking-widest hover:bg-white/10 hover:border-primary/50 transition-all hidden sm:flex"
          >
            {isSyncing ? <Loader2 className="h-3.5 w-3.5 mr-2 animate-spin text-primary" /> : <Github className="h-3.5 w-3.5 mr-2" />}
            {isSyncing ? 'Pushing...' : 'Sync_GitHub'}
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleSave}
            className={`h-9 bg-white/5 border-white/10 text-white font-bold text-[10px] uppercase tracking-widest hover:bg-white/10 transition-all ${isSaving ? 'border-primary text-primary' : ''}`}
          >
            {isSaving ? <Check className="h-3.5 w-3.5 mr-2 animate-in fade-in" /> : <Save className="h-3.5 w-3.5 mr-2 text-primary" />}
            {isSaving ? 'Stored' : 'Save'}
          </Button>
          <Button size="sm" className="h-9 bg-accent hover:bg-accent/90 text-white font-bold text-[10px] uppercase tracking-widest neo-button">
            <Play className="h-3.5 w-3.5 mr-2 fill-current" /> Play_Sim
          </Button>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden">
        {/* Left Sidebar - Scene Hierarchy */}
        <aside className="w-64 border-r border-white/5 bg-black/60 flex flex-col z-40 backdrop-blur-md">
          <div className="p-4 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-[9px] font-black text-white/30 uppercase tracking-[0.3em]">Quick_Tools</h3>
            </div>
            <div className="grid grid-cols-4 gap-1.5">
              {[MousePointer2, Move, Maximize2, Box].map((Icon, i) => (
                <Button key={i} variant="ghost" size="icon" className={`h-10 w-full rounded-lg border ${i === 0 ? 'border-primary/40 bg-primary/10 text-primary shadow-[0_0_10px_rgba(14,165,233,0.2)]' : 'border-white/5 text-white/30 hover:text-white'}`}>
                  <Icon className="h-4 w-4"/>
                </Button>
              ))}
            </div>
          </div>
          <Separator className="bg-white/5" />
          <ScrollArea className="flex-1">
            <div className="p-4 space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-[9px] font-black text-white/30 uppercase tracking-[0.3em]">Scene_Node_Tree</h3>
                <Plus className="h-3 w-3 text-white/20 hover:text-primary cursor-pointer transition-colors" />
              </div>
              <div className="space-y-0.5">
                {['Main', 'World', 'Player', 'Enemies', 'Collectibles', 'Environment', 'UI_Layer'].map((item) => (
                  <Button 
                    key={item} 
                    variant="ghost"
                    className={`w-full justify-start text-[11px] h-9 transition-all rounded-md group ${selectedElement === item ? 'bg-primary/5 text-primary border-l-2 border-primary rounded-l-none' : 'text-white/40 hover:text-white/80'}`}
                    onClick={() => setSelectedElement(item)}
                  >
                    <ChevronRight className={`h-3 w-3 mr-1.5 transition-transform ${item === 'World' || item === 'Main' ? 'rotate-90 text-primary' : 'opacity-10'}`} />
                    <Layers className={`h-3.5 w-3.5 mr-2.5 transition-colors ${selectedElement === item ? 'text-primary' : 'text-white/10'}`} />
                    <span className="font-bold tracking-tight uppercase">{item}</span>
                  </Button>
                ))}
              </div>
            </div>
          </ScrollArea>
        </aside>

        {/* Center - Viewport */}
        <main className="flex-1 bg-[#050505] relative p-4 overflow-hidden flex flex-col">
          <div className="bg-[#080808] border border-white/5 rounded-xl flex-1 relative overflow-hidden flex items-center justify-center shadow-2xl">
             <div className="absolute inset-0 opacity-20 pointer-events-none" style={{ backgroundImage: 'linear-gradient(#111 1px, transparent 1px), linear-gradient(90deg, #111 1px, transparent 1px)', backgroundSize: '40px 40px' }} />
             
             {/* Simulated Game Preview */}
             <div className="flex flex-col items-center gap-6 z-10 animate-float">
                <div className="relative group">
                  <div className="absolute inset-0 bg-primary blur-[60px] opacity-10 group-hover:opacity-30 transition-opacity" />
                  <div className="w-24 h-24 rounded-3xl bg-black border border-primary/20 flex items-center justify-center relative shadow-[0_0_40px_rgba(14,165,233,0.1)]">
                    <Gamepad2 className="h-12 w-12 text-primary" />
                  </div>
                </div>
                <div className="space-y-1 text-center">
                  <p className="font-headline font-bold text-lg tracking-tighter text-white uppercase">Waiting_For_Execution</p>
                  <div className="flex items-center gap-2 justify-center">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
                    <p className="text-[9px] font-mono text-white/30 uppercase tracking-[0.4em]">Engine_Core: Operational</p>
                  </div>
                </div>
             </div>
             
             {/* HUD Overlays */}
             <div className="absolute top-6 left-6 flex items-center gap-4 bg-black/60 backdrop-blur-md px-4 py-2 rounded-lg border border-white/5 shadow-xl">
                <Activity className="h-3.5 w-3.5 text-green-500" />
                <div className="text-[9px] font-mono text-white/60 tracking-[0.2em] uppercase">
                  Engine_FPS: <span className="text-green-500 font-bold">144.0</span>
                </div>
             </div>

             <div className="absolute bottom-6 left-6 right-6 flex justify-between items-end pointer-events-none">
                <div className="h-32 w-48 border-l border-b border-white/10 rounded-bl-xl p-4 flex flex-col justify-end gap-2">
                   <div className="w-full h-1 bg-white/5 rounded-full overflow-hidden">
                      <div className="h-full bg-primary w-[70%]" />
                   </div>
                   <span className="text-[8px] font-mono text-primary/40 uppercase">Memory_Buffer</span>
                </div>
             </div>
          </div>

          {/* Bottom AI Prompt Bar */}
          <div className="mt-4 bg-black/40 border border-white/5 rounded-xl p-3 flex items-center gap-4 group focus-within:border-primary/30 transition-all">
            <div className="bg-primary/10 p-2.5 rounded-lg text-primary border border-primary/20 group-hover:scale-110 transition-transform">
              <Zap className="h-5 w-5 fill-current" />
            </div>
            <Input 
              placeholder="Ex: Altere a gravidade para 1200 e adicione lógica de pulo duplo..." 
              className="flex-1 border-none bg-transparent h-10 text-sm text-white placeholder:text-white/20 focus-visible:ring-0"
            />
            <Button className="bg-primary hover:bg-primary/90 text-black font-headline font-bold h-10 px-6 neo-button rounded-lg text-xs uppercase tracking-widest">
              Forge_Change
            </Button>
          </div>
        </main>

        {/* Right Sidebar - Inspector & IDE */}
        <aside className="w-96 border-l border-white/5 bg-black/60 hidden lg:flex flex-col z-40 backdrop-blur-md">
          <Tabs defaultValue="code" className="flex-1 flex flex-col">
            <div className="px-2 border-b border-white/5 bg-black/40">
              <TabsList className="w-full bg-transparent p-0 gap-2 h-12">
                <TabsTrigger value="inspector" className="data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none h-full px-4 font-black text-[9px] uppercase tracking-[0.2em] text-white/30 data-[state=active]:text-primary">Inspector</TabsTrigger>
                <TabsTrigger value="code" className="data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none h-full px-4 font-black text-[9px] uppercase tracking-[0.2em] text-white/30 data-[state=active]:text-primary">Neural_IDE</TabsTrigger>
              </TabsList>
            </div>
            
            <ScrollArea className="flex-1">
              <TabsContent value="inspector" className="p-5 m-0 space-y-6">
                {selectedElement ? (
                  <>
                    <div className="space-y-1 bg-white/5 p-3 rounded-lg border border-white/5">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="font-headline font-bold text-xs text-white uppercase tracking-tighter">Node: {selectedElement}</h4>
                        <span className="text-[7px] bg-primary/20 text-primary px-1.5 py-0.5 rounded font-black">2D_PHYSICS</span>
                      </div>
                      <p className="text-[9px] text-white/20 font-mono">TYPE: CHARACTER_BODY_2D</p>
                    </div>

                    <div className="space-y-6">
                      {[
                        { label: 'Movement Speed', key: 'speed', max: 1000, suffix: 'px/s' },
                        { label: 'Health Pool', key: 'health', max: 200, suffix: 'HP' },
                        { label: 'Gravity Factor', key: 'gravity', max: 2000, suffix: 'G' }
                      ].map((prop) => (
                        <div key={prop.key} className="space-y-2.5">
                          <div className="flex justify-between items-center">
                            <label className="text-[9px] font-black text-white/30 uppercase tracking-widest">{prop.label}</label>
                            <span className="text-[10px] text-primary font-mono font-bold">{(properties as any)[prop.key]}{prop.suffix}</span>
                          </div>
                          <Slider 
                            defaultValue={[(properties as any)[prop.key]]} 
                            max={prop.max} 
                            min={0}
                            step={1} 
                            onValueChange={(val) => setProperties(p => ({...p, [prop.key]: val[0]}))}
                            className="[&_[role=slider]]:h-3 [&_[role=slider]]:w-3 [&_[role=slider]]:border-primary"
                          />
                        </div>
                      ))}
                    </div>
                  </>
                ) : (
                  <div className="flex flex-col items-center justify-center py-24 text-center space-y-4 opacity-10">
                    <MousePointer2 className="h-10 w-10" />
                    <p className="text-[10px] font-bold uppercase tracking-widest">Select_Node_Link</p>
                  </div>
                )}
              </TabsContent>

              <TabsContent value="code" className="p-0 m-0 h-full flex flex-col">
                <div className="flex items-center justify-between px-4 py-2 border-b border-white/5 bg-white/5">
                   <div className="flex items-center gap-2">
                      <Terminal className="h-3 w-3 text-primary" />
                      <span className="text-[9px] font-black uppercase tracking-[0.2em] text-white/60">Script_Editor v2.5</span>
                   </div>
                   <Button variant="ghost" size="icon" className="h-6 w-6 text-white/20 hover:text-primary transition-colors" onClick={() => toast({ title: "Refatoração AI", description: "Código limpo e otimizado." })}>
                      <RefreshCcw className="h-3 w-3" />
                   </Button>
                </div>
                
                <div className="relative flex-1">
                  <div className="absolute top-0 left-0 w-8 h-full bg-[#0a0a0a] border-r border-white/5 flex flex-col items-center py-4 gap-[2.4px]">
                     {Array.from({length: 40}).map((_, i) => (
                       <span key={i} className="text-[9px] font-mono text-white/10 select-none leading-[1.625rem] h-[1.625rem]">{i + 1}</span>
                     ))}
                  </div>
                  <Textarea 
                    value={scriptContent}
                    onChange={(e) => setScriptContent(e.target.value)}
                    className="flex-1 w-full bg-[#0a0a0a] border-none text-primary/80 font-mono text-[11px] leading-relaxed p-4 pl-12 h-[calc(100vh-180px)] focus-visible:ring-0 resize-none selection:bg-primary/20 custom-scrollbar"
                    spellCheck={false}
                  />
                </div>
                
                <div className="p-4 bg-black/60 border-t border-white/5">
                   <Button 
                    className="w-full h-10 bg-white/5 hover:bg-white/10 border border-white/10 text-white font-bold text-[10px] uppercase tracking-widest neo-button"
                    onClick={() => {
                      handleSave();
                    }}
                   >
                     <Zap className="h-3.5 w-3.5 mr-2 text-primary fill-current" /> Compile_&_Store
                   </Button>
                </div>
              </TabsContent>
            </ScrollArea>
          </Tabs>
        </aside>
      </div>

      <style jsx global>{`
        .custom-scrollbar::-webkit-scrollbar { width: 4px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.05); border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(14, 165, 233, 0.2); }
      `}</style>
    </div>
  );
}